version: '3'
services:
 CycleGanTurbo-python310 :
   build:
     context: .
     dockerfile: Dockerfile
   image: img2imgturbo:py310
   working_dir: /workdir
   command: bash
   stdin_open: true
   tty: true
   shm_size: 1g
   network_mode: host
   ulimits:
     memlock: -1
     stack: 67108864
   environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - TF_ENABLE_AUTO_MIXED_PRECISION=1
   ports:
     - "6006:6006"
   volumes:
     - .:/workdir
     - /media/domore_rackstation2_vol2:/media/domore_rackstation2_vol2
